
export const GET_USER_FETCH = 'GET_USER_FETCH';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_PHOTO_FETCH = 'GET_PHOTO_FETCH';
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS';